export const ActionTypes={
    SET_PRODUCTS:'SET_PRODUCTS',
    SELECTED_PRODUCT:'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT:'REMOVE_SELECTED_PRODUCT',
    GET_ALL_CATEGORIES:' GET_ALL_CATEGORIES',
    SELECTED_CATEGORY:'SELECTED_CATEGORY',
    SELECTED_CATEGORY_PRODUCTS:'SELECTED_CATEGORY_PRODUCTS'
}